version: "3.0"
services:
  go:
    image: h3poteto/golang:1.11.2
    working_dir: /go/src/github.com/h3poteto/envoy_example/backend/http
    environment:
      PORT: 9090
    volumes:
      - ./backend/http:/go/src/github.com/h3poteto/envoy_example/backend/http
    entrypoint: sh -c
    command: |
      "dep ensure && \
      go run main.go"

  envoy:
    image: envoyproxy/envoy:latest
    links:
      - go:go
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "10000:10000"
