version: "3.0"
services:
  http:
    image: h3poteto/golang:1.11.2
    working_dir: /go/src/github.com/h3poteto/envoy_example/backend/http
    environment:
      PORT: 9090
    volumes:
      - ./backend/http:/go/src/github.com/h3poteto/envoy_example/backend/http
    entrypoint: sh -c
    command: |
      "dep ensure && \
      go run main.go"

  grpc:
    image: h3poteto/grpc-go:1.11.4
    working_dir: /go/src/github.com/h3poteto/envoy_example/backend/grpc
    environment:
      PORT: 9091
    volumes:
      - .:/go/src/github.com/h3poteto/envoy_example/
    entrypoint: sh -c
    command: |
      "dep ensure && \
      go run main.go"

  envoy:
    image: envoyproxy/envoy:latest
    links:
      - http:http
      - grpc:grpc
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "12000:12000"
      - "10000:10000"
